# Generated by Django 6.0.1 on 2026-01-11 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID from external tennis data source', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=3)),
                ('picture_path', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('association', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('surface', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('external_id', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=50)),
                ('points_earned', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tennis.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tennis.tournament')),
            ],
            options={
                'ordering': ['tournament__start_date'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='tennis.player')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
